# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SCPI_Terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(785, 412)
        MainWindow.setMinimumSize(QtCore.QSize(0, 412))
        MainWindow.setStyleSheet("background-color: rgb(23,23,23);\n"
"color:#DCDCDC;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QToolTip { \n"
"       background-color: rgb(50,50,50); \n"
"       color: white; \n"
"       border: black solid 1px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 7, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setMinimumSize(QtCore.QSize(520, 230))
        self.frame_6.setStyleSheet("QFrame{\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textBrowser_terminal_view = QtWidgets.QTextBrowser(self.frame_6)
        self.textBrowser_terminal_view.setToolTip("")
        self.textBrowser_terminal_view.setStyleSheet("QTextBrowser{\n"
"    border: None;\n"
"    background-color: transparent;\n"
"    font-size: 18px;\n"
"}")
        self.textBrowser_terminal_view.setObjectName("textBrowser_terminal_view")
        self.verticalLayout_4.addWidget(self.textBrowser_terminal_view)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_help = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_help.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_help.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_help.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_help.setToolTipDuration(5000)
        self.pushButton_help.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(23, 23, 25);\n"
"    \n"
"    image: url(:/icons/icons8-pregunta-25.png);\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(38, 40, 38);\n"
"}")
        self.pushButton_help.setText("")
        self.pushButton_help.setObjectName("pushButton_help")
        self.horizontalLayout_2.addWidget(self.pushButton_help)
        self.comboBox_commands_list = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_commands_list.setMinimumSize(QtCore.QSize(124, 40))
        self.comboBox_commands_list.setMaximumSize(QtCore.QSize(16777215, 40))
        self.comboBox_commands_list.setToolTipDuration(5000)
        self.comboBox_commands_list.setStyleSheet("QComboBox {\n"
"    border: 2px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    min-width: 6em;\n"
"    font: 16px;\n"
"    color: #dcdcDC;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    \n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     \n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"     \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 5px;\n"
"    \n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(23,23,23)  ;\n"
"}")
        self.comboBox_commands_list.setObjectName("comboBox_commands_list")
        self.horizontalLayout_2.addWidget(self.comboBox_commands_list)
        self.pushButton_pass_command = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_pass_command.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_pass_command.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_pass_command.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_pass_command.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    border: none;\n"
"    font: 15px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    \n"
"    image: url(:/icons/icons8-abajo-2-25.png);\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(50, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}")
        self.pushButton_pass_command.setText("")
        self.pushButton_pass_command.setObjectName("pushButton_pass_command")
        self.horizontalLayout_2.addWidget(self.pushButton_pass_command)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    border: none;\n"
"    font: 15px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(50, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_data = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_data.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_data.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit_data.setStyleSheet("QLineEdit{\n"
"    border-radius: 10px;\n"
"    background-color: transparent;\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    font-size: 18px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"}")
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.horizontalLayout_3.addWidget(self.lineEdit_data)
        self.pushButton_send = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_send.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_send.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_send.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_send.setToolTipDuration(5000)
        self.pushButton_send.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/icons/icons8-lleno-enviado-25.png);\n"
"}")
        self.pushButton_send.setText("")
        self.pushButton_send.setObjectName("pushButton_send")
        self.horizontalLayout_3.addWidget(self.pushButton_send)
        self.pushButton_clean = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_clean.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_clean.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_clean.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clean.setToolTipDuration(5000)
        self.pushButton_clean.setStyleSheet("QPushButton{\n"
"    \n"
"    image: url(:/icons/icons8-eliminar-25.png);\n"
"}")
        self.pushButton_clean.setText("")
        self.pushButton_clean.setObjectName("pushButton_clean")
        self.horizontalLayout_3.addWidget(self.pushButton_clean)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setMinimumSize(QtCore.QSize(160, 160))
        self.frame_9.setMaximumSize(QtCore.QSize(160, 160))
        self.frame_9.setStyleSheet("QFrame{\n"
"    border-radius: 80px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 120, 250, 255));\n"
"    image: url(:/img/usb.png);\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4.addWidget(self.frame_9)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_5.setSpacing(9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.comboBox_instruments_list = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_instruments_list.setMinimumSize(QtCore.QSize(124, 40))
        self.comboBox_instruments_list.setMaximumSize(QtCore.QSize(230, 40))
        self.comboBox_instruments_list.setToolTipDuration(5000)
        self.comboBox_instruments_list.setStyleSheet("QComboBox {\n"
"    border: 2px;\n"
"    border-radius: 10px;\n"
"    padding-left: 10px;\n"
"    min-width: 6em;\n"
"    font: 16px;\n"
"    color: #dcdcDC;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    \n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"     \n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"     \n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 22px;\n"
"\n"
"    border-left-width: 5px;\n"
"    \n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    \n"
"    image: url(:/icons/icons8-clasificar-abajo-15.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"\n"
"}\n"
"\n"
"QLabel {\n"
"    font: 18px;\n"
"    color:#DCDCDC;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: rgb(23,23,23)  ;\n"
"}")
        self.comboBox_instruments_list.setObjectName("comboBox_instruments_list")
        self.verticalLayout_5.addWidget(self.comboBox_instruments_list)
        self.pushButton_refresh = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_refresh.setMinimumSize(QtCore.QSize(230, 40))
        self.pushButton_refresh.setMaximumSize(QtCore.QSize(230, 40))
        self.pushButton_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_refresh.setToolTipDuration(5000)
        self.pushButton_refresh.setStyleSheet("QPushButton{\n"
"    border-radius: 10px;\n"
"    background-color: transparent;\n"
"    color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    border: 2px solid qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"    font: 14px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.534091, x2:1, y2:0.545455, stop:0 rgba(0, 85, 255, 255), stop:1 rgba(71, 129, 255, 255));\n"
"color:#DCDCDC;\n"
"}")
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.verticalLayout_5.addWidget(self.pushButton_refresh)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame_3)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SCPI Terminal"))
        self.pushButton_help.setToolTip(_translate("MainWindow", "<html><head/><body><p>Open <span style=\" font-weight:600;\">Spectrum Analyzer User Manual.</span></p></body></html>"))
        self.comboBox_commands_list.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">SCPI</span> Commands list.</p></body></html>"))
        self.lineEdit_data.setPlaceholderText(_translate("MainWindow", "INSERT DATA HERE"))
        self.pushButton_send.setToolTip(_translate("MainWindow", "Send data"))
        self.pushButton_clean.setToolTip(_translate("MainWindow", "Clean Terminal."))
        self.label.setText(_translate("MainWindow", "INSTRUMENT SELECT:"))
        self.comboBox_instruments_list.setToolTip(_translate("MainWindow", "Instruments list."))
        self.pushButton_refresh.setToolTip(_translate("MainWindow", "Refresh instruments list."))
        self.pushButton_refresh.setText(_translate("MainWindow", "REFRESH LIST"))
        self.label_2.setText(_translate("MainWindow", "Created by <strong>Allione Joaquín</strong>"))
import resources_rc
